# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  
  config.vm.box = "hashicorp/precise64"
  
  #refer to http://berkshelf.com/
  config.berkshelf.enabled = true

  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "apt"    
    chef.add_recipe "git"
    chef.add_recipe "vim"
    chef.add_recipe "python"
    chef.add_recipe "time"  

  end

  config.vm.provision "shell" do |s|
    s.inline = "pip install XlsxWriter"
  end

  
end
